version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ml-pipeline

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    platform: linux/amd64
    ports:
      - "5050:5050"
    environment:
      - BACKEND_STORE_URI=mysql://root:password@mysql/mlflow    # Do not replace with ${BACKEND_STORE_URI}
      - MLFLOW_USER=${MLFLOW_USER}
      - MLFLOW_PASSWORD=${MLFLOW_PASSWORD}
      - MLFLOW_ARTIFACT_URI=/mnt/mlflow_store
    depends_on:
      - zenml
      - mysql
    networks:
      - ml-pipeline
    volumes:
      - /Users/mlevydaniel/Desktop/zenml-integration/mlflow_store:/mnt/mlflow_store

  zenml:
    image: zenmldocker/zenml-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - ZENML_STORE_URL=mysql://root:password@mysql/zenml   # Do not replace with ${ZENML_STORE_URL}
      - ZENML_ARTIFACT_STORE=/mnt/zenml_store
    user: "${UID}:${GID}"
    depends_on:
      - mysql
    networks:
      - ml-pipeline
    volumes:
      - /Users/mlevydaniel/Desktop/zenml-integration/zenml_store:/mnt/zenml_store

volumes:
  mysql_data:
  mlflow_store:
  zenml_store:

networks:
  ml-pipeline: