# Use an official Python runtime as a parent image
FROM python:3.12

# Set the working directory
WORKDIR /app

# Update pip to the latest version and install Python dependencies
RUN pip install --upgrade pip
RUN pip install mysqlclient mlflow

# Expose the MLflow tracking server port
EXPOSE 5050

# Command to run MLflow server
CMD mlflow server --backend-store-uri ${BACKEND_STORE_URI} --default-artifact-root ${MLFLOW_ARTIFACT_URI} --host 0.0.0.0 --port 5050
