# Use an official Python runtime as a parent image
FROM python:3.12

# Set the working directory
WORKDIR /app

# Update pip to the latest version
RUN pip install --upgrade pip

# Install MLflow
RUN pip install mlflow psycopg2-binary

# Expose the MLflow tracking server port
EXPOSE 5050

# Command to run MLflow server
CMD mlflow server --backend-store-uri ${BACKEND_STORE_URI} --default-artifact-root /mlflow --host 0.0.0.0 --port 5050
