version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ml-pipeline

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    platform: linux/amd64
    ports:
      - "5050:5050"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5050
      - BACKEND_STORE_URI=mysql://root:password@mysql/mlflow
    depends_on:
      - zenml
      - mysql
    networks:
      - ml-pipeline

  zenml:
    image: zenmldocker/zenml-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - ZENML_STORE_URL=mysql://root:password@mysql/zenml
    depends_on:
      - mysql
    networks:
      - ml-pipeline

volumes:
  mysql_data:

networks:
  ml-pipeline: