version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ml-pipeline

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ml-pipeline

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5050:5050"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5050
      - BACKEND_STORE_URI=postgresql://admin:secret@postgres:5432/mlflow
    depends_on:
      - zenml
      - postgres
    networks:
      - ml-pipeline

  zenml:
    image: zenmldocker/zenml-server:latest
    ports:
      - "8080:8080"
    environment:
      - ZENML_STORE_URL=mysql://root:password@mysql/zenml
    depends_on:
      - mysql
    networks:
      - ml-pipeline

volumes:
  mysql_data:
  postgres_data:

networks:
  ml-pipeline: